### ISSUE TITLE
AttributeError: 'DeviceArray' object has no attribute 'observation'

### ISSUE THREAD

**Issue by hn2** [henry-prior/jax-rl#12]
When running the code I get:

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_49/2609719913.py in <module>
      6 
      7 temp_timestep = env.reset()
----> 8 state_dim = flat_obs(temp_timestep.observation).shape[0]
      9 action_dim = env.action_spec().shape[0]
     10 max_action = float(env.action_spec().maximum[0])

AttributeError: 'DeviceArray' object has no attribute 'observation'

**Comment by henry-prior** [comment]
Can you please give some details about:
- What command you're running
- Any local changes you've made
- The machine you're running on (OS, CPU manufacturer, GPU if applicable)

**Comment by hn2** [comment]
I am trying to implement custom env with your code. I now get:


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_46/149212032.py in <module>
     49 train_loop = TRAIN_LOOPS[args.policy]
     50 
---> 51 train_loop(args, policy, replay_buffer, env)

/tmp/ipykernel_46/1511689711.py in base_train_loop(args, policy, replay_buffer, env)
      1 def base_train_loop(args: dict, policy, replay_buffer: ReplayBuffer, env):
----> 2     evaluations = [eval_policy(env, policy, args.domain_name, args.task_name, args.seed)]
      3 
      4     timestep = env.reset()
      5     episode_reward = 0

/tmp/ipykernel_46/3982767400.py in eval_policy(env, policy, domain_name, task_name, seed, eval_episodes)
      7     for _ in range(eval_episodes):
      8         timestep = eval_env.reset()
----> 9         while not timestep.last():
     10             action = policy.select_action(flat_obs(timestep.observation))
     11             timestep = eval_env.step(action)

AttributeError: 'DeviceArray' object has no attribute 'last'

Why would resetting the env return the total timestep?
timestep = eval_env.reset()
This should return observation?

**Comment by hn2** [comment]
In addition, how can I use env/custom env without dm_control suite which requires mojoco engine?

**Comment by henry-prior** [comment]
> I am trying to implement custom env with your code. I now get:

If possible, try changing your environment to adhere to the same format as the DeepMind Control Suite. You can find their base `Environment` class here:
https://github.com/deepmind/dm_control/blob/4cf89ef1a0d99f7e9f70b3f5ad0bf2a685cbd935/dm_control/rl/control.py#L28
And the `timestep` object should be a `NamedTuple` as defined here: https://github.com/deepmind/dm_env/blob/abee135a07cc8e684173586dc8a20e696bbd40fb/dm_env/_environment.py#L25

Hope this helps!

**Comment by henry-prior** [comment]
> In addition, how can I use env/custom env without dm_control suite which requires mojoco engine?

I think my above answer should help with adding a custom env. MuJoCo is now free and open source if that was your main concern. The README of this repo has details on how to install.

**Comment by hn2** [comment]
Mojoco is a pain to install on linux and I don't really need it. Is there a workaround?

**Comment by henry-prior** [comment]
For a custom env as long as your `timestep` object has the same format as the class I linked above it should work but I haven't tested it

**Comment by hn2** [comment]
Is it possible to modify your code to not using dm_control at all and use the original gym env?

**Comment by henry-prior** [comment]
As long as you have your own environment that you can initialize in place of the calls to `suite.load` you won't have to make any other changes. In terms of the code I linked above it doesn't depend on other libraries that much so you should be able to just copy those classes or the general structure of them and wrap your environment in it. 

There's also this package but it's the wrong direction from what you're looking for. Might still be useful to consult for the differences.

**Comment by hn2** [comment]
I am not sure that I understood your last post. My custom env is a gym.env and I can instantiate it.  What other changes to my or your code do I need?

**Comment by henry-prior** [comment]
I made a PR adding gym support. Please let me know if this works for you, you'll need to use the new file `main_gym.py` instead of `main_dm_control.py`: https://github.com/henry-prior/jax-rl/pull/13 I'll work on cleaning it up and merging it this week.

**Comment by hn2** [comment]
When do you believe you will have something to test?

**Comment by henry-prior** [comment]
You can pull the branch from that PR, `gym-support` and test it now.

**Comment by hn2** [comment]
Can you please merge the gym-support with  the master branch?

I tried to clone the gym-support branch but it is creating another jax-rl folder and it does not work properly.

I did this in my linux machine:

git clone --branch gym-support https://github.com/henry-prior/jax-rl.git

I now have jax-rl folder and inside of it another jax-rl folder with your code.

I tried:

python jax_rl/main_gym.py --policy SAC --max_timesteps 10000

I get:

Traceback (most recent call last):

  File "jax_rl/main_gym.py", line 8, in <module>

    from MPO import MPO

  File "/home/ubuntu/install/jax-rl/jax_rl/MPO.py", line 16, in <module>

    from jax_rl.buffers import ReplayBuffer

ModuleNotFoundError: No module named 'jax_rl'

**Comment by henry-prior** [comment]
I need to clean the branch up before merging it. Did you run `make init` first? Also the best way to get the new branch locally would not be to clone it but to:
```bash
git checkout master
git pull
git checkout -b gym-support origin/gym-support
```

**Comment by hn2** [comment]
What does make init do?

**Comment by henry-prior** [comment]
It builds a new poetry environment and downloads all dependencies as well as initializes `jax-rl` as a local python package

**Comment by hn2** [comment]
I am actually planning to run this code in kaggle as notebook.

**Comment by henry-prior** [comment]
By copying the code into the notebook? I don't think I can help you with that part of the process

**Comment by hn2** [comment]
Hi,

I succeeded to start training, then I get this error:

 

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

/tmp/ipykernel_65/4278832167.py in <module>

     45 train_loop = TRAIN_LOOPS[args.policy]

     46 

---> 47 train_loop(args, policy, replay_buffer, env)

 

/tmp/ipykernel_65/15286188.py in gym_train_loop(args, policy, replay_buffer, env)

     36                     )

     37                 else:

---> 38                     policy.train(replay_buffer, args.batch_size)

     39 

     40         if done:

 

/tmp/ipykernel_65/1425453587.py in train(self, replay_buffer, batch_size)

    198 

    199         target_Q = jax.lax.stop_gradient(

--> 200             get_td_target(next(self.rng), *buffer_out, *self.target_params)

    201         )

    202 

 

    [... skipping hidden 13 frame]

 

/opt/conda/lib/python3.7/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)

    164 

    165     try:

--> 166       ans = self.f(*args, **dict(self.params, **kwargs))

    167     except:

    168       # Some transformations yield from inside context managers, so we have to

 

TypeError: get_td_target() takes 11 positional arguments but 12 were given

**Comment by hn2** [comment]
I also got this error with my own custom env (the previous mail was with Pendulum-v0):

Any idea what this can be and where to start debugging this?

 

eval_policy---------------------------------------------------------------------------

ScopeParamShapeError                      Traceback (most recent call last)

/tmp/ipykernel_45/3861124716.py in <module>

     46 train_loop = TRAIN_LOOPS[args.policy]

     47 

---> 48 train_loop(args, policy, replay_buffer, env)

 

/tmp/ipykernel_45/15286188.py in gym_train_loop(args, policy, replay_buffer, env)

      1 def gym_train_loop(args: dict, policy, replay_buffer: ReplayBuffer, env):

----> 2     evaluations = [_gym(policy, args.env, args.seed)]

      3 

      4     state, done = env.reset(), False

      5     episode_reward = 0

 

/tmp/ipykernel_45/1642912942.py in eval_policy_gym(policy, env_name, seed, eval_episodes)

      7         state, done = eval_env.reset(), False

      8         while not done:

----> 9             action = policy.select_action(np.array(state))

     10             state, reward, done, _ = eval_env.step(action)

     11             avg_reward += reward

 

/tmp/ipykernel_45/1425453587.py in select_action(self, state)

    176             None,

    177             False,

--> 178             False,

    179         )

    180         return mu.flatten()

 

    [... skipping hidden 14 frame]

 

/tmp/ipykernel_45/3842203696.py in apply_gaussian_policy_model(params, action_dim, max_action, state, key, sample, MPO)

    195 ) -> jnp.ndarray:

    196     return GaussianPolicy(action_dim=action_dim, max_action=max_action).apply(

--> 197         dict(params=params), state, key=key, sample=sample, MPO=MPO

    198     )

 

    [... skipping hidden 7 frame]

 

/tmp/ipykernel_45/3842203696.py in __call__(self, x, key, sample, MPO)

     69     @nn.compact

     70     def __call__(self, x, key=None, sample=False, MPO=False):

---> 71         x = nn.Dense(features=200)(x)

     72         x = nn.LayerNorm()(x)

     73         x = nn.tanh(x)

 

    [... skipping hidden 3 frame]

 

/opt/conda/lib/python3.7/site-packages/flax/linen/linear.py in __call__(self, inputs)

    178                         self.kernel_init,

    179                         (inputs.shape[-1], self.features),

--> 180                         self.param_dtype)

    181     kernel = jnp.asarray(kernel, self.dtype)

    182     y = lax.dot_general(inputs, kernel,

 

    [... skipping hidden 1 frame]

 

/opt/conda/lib/python3.7/site-packages/flax/core/scope.py in param(self, name, init_fn, *init_args)

    727         if jnp.shape(val) != jnp.shape(abs_val):

    728           raise errors.ScopeParamShapeError(name, self.path_text,

--> 729               jnp.shape(val), jnp.shape(abs_val))

    730     else:

    731       if not self.is_mutable_collection('params'):

 

ScopeParamShapeError: Inconsistent shapes between value and initializer for parameter "kernel" in "/Dense_0": (300, 200), (3, 200). ( <https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.ScopeParamShapeError> https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.ScopeParamShapeError)
