### ISSUE TITLE
The seed hasn't been passed into the agent's class

### ISSUE THREAD

**Issue by zhaoyi11** [henry-prior/jax-rl#9]

**Comment by zhaoyi11** [comment]
The seed hasn't been passed into the agent's class, thus the seed inside the agent class is always 0. 
https://github.com/henry-prior/jax-rl/blob/a2c606789b1e883785b46f5a73e5840220cc86b2/jax_rl/main_dm_control.py#L114

**Comment by henry-prior** [comment]
Good catch, thanks!
